"""add phone number

Revision ID: 3599fa5ab0b3
Revises: 45baaa8fafbe
Create Date: 2024-10-08 09:30:33.405284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3599fa5ab0b3'
down_revision: Union[str, None] = '45baaa8fafbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'Posts', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    op.drop_constraint(None, 'Posts', type_='foreignkey')
    # ### end Alembic commands ###
